### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by ghost** [gaenseklein/repfiles#2]
### Environment

- Operating System: Ubuntu 22.04.03 LTS
- Micro Version: 2.0.13
- repfiles version: 1.0.0

### Description of the bug

Use the option `"repfiles.auto_close_after_open": false`, it is not possible to open more than one file.

### How to reproduce the the bug ?
1. set the option `"repfiles.auto_close_after_open": false` and reopen the micro editor;
2. Run `repfiles` in the editor command bar and open a file;
3. Go back to repfile and open another file (with enter or tab);

### Expected behavior ?

Two files are open.

### Result obtained?

Step 3 is not executed and no more files can be opened.

**Comment by gaenseklein** [comment]
thx for the feedback. 
i cant reproduce what you described, but found another bug maybe related to that. after closing a view-pane which was target_pane for repfiles and not closing repfiles opening files with tab crashed the system (nil-pointer deference). never caught that bug because i use auto_close since i incorporated it.

**Comment by ghost** [comment]
I retested it with the code in the man branch and it's ok

**Comment by gaenseklein** [comment]
thx for the feedback
